
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: establishments
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: fastapi_backend
    command: uv run --env prod
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/establishments
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
